### ISSUE TITLE
New subprocess error "detected dubious ownership in repository at '/github/workspace'"

### ISSUE THREAD

**Issue by dmarkey** [py-cov-action/python-coverage-comment-action#127]
```
subprocess.CalledProcessError: Command '('git', 'fetch', '--depth=1000')' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coverage_comment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 39, in main
    exit_code = action(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 76, in action
    return generate_comment(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 108, in generate_comment
    diff_coverage = coverage_module.get_diff_coverage_info(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/coverage.py", line 187, in get_diff_coverage_info
    subprocess.run("git", "fetch", "--depth=1000")
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 25, in run
    raise SubProcessError("/n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: /nfatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
```

Something seems to have changed the end of January.. git version upgrade perhaps?

**Comment by ewjoachim** [comment]
Strange :/ We could call `git config --global --add safe.directory '...'` but I'd like to understand where this comes from. I don't think I reproduce in my repos using the project. Would you happen to have a link or something ?

**Comment by dmarkey** [comment]
I'm afraid they're deployed to private repos :(

**Comment by ellisvalentiner** [comment]
@dmarkey are you using self-hosted runners?

**Comment by dmarkey** [comment]
I am not, I am however using this as part of a composite action?

```
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "junit.xml"
    - name: Coverage Report
      if: always()
      id: coverage_comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
          GITHUB_TOKEN: ${{ inputs.gh-token }}
    ```

**Comment by JeffreyThiessen** [comment]
I also encountered this error today while trying to add test coverage to our integration testing. Here is a link to the job: https://github.com/phac-nml/irida-uploader/actions/runs/4049019870/jobs/6965055676

I also came across this thread where others are having similar issues with runner images: https://github.com/actions/runner-images/issues/6775

**Comment by ewjoachim** [comment]
I've merged #129 to the v3 branch, which supposedly fixes the issue. Please let me know of you still experience issues in the v3 branch.

**Comment by ewjoachim** [comment]
> I also came across this thread where others are having similar issues with runner images: [actions/runner-images#6775](https://github.com/actions/runner-images/issues/6775)

Ah, just saw that link. Yes, it seems to be the issue ! I can improve the error message now.

**Comment by ewjoachim** [comment]
Well at least https://github.com/py-cov-action/python-coverage-comment-action/pull/128 started working after the fix.

Sorry you folks had a failing CI for 24h :sweat_smile:

**Comment by dmarkey** [comment]
Thanks everyone!
