### ISSUE TITLE
Action can't find source code to report

### ISSUE THREAD

**Issue by ArthurNRL** [py-cov-action/python-coverage-comment-action#162]
I'm facing an error, followed the instruction, error says its permission but it doesn't matter the permission I set.
Here's the debug logs minus folder paths("redacted" is my main package), after this it jjust repeats the last few lines for every file in the project
https://pastebin.com/rcv95F7b

```
##.coveragerc
[run]

branch = True
dynamic_context = test_function
source = redacted
relative_files = True

[report]
precision = 2
sort = Miss
show_missing = True
ignore_errors = True

[html]
show_contexts = True
```
the generation works locally

**Comment by ewjoachim** [comment]
I'm surprised to see a backslash in a path in your log: `redacted\__init__.py`. I'd tend to investigate where this comes from and fix that.

(is it possible that the `.coverage` file is created in a windows context? I believe this action hasn't been tested on windows-generated .coverage files. Does it mean we need to figure out a way to use .coverage files with `\` inside an ubuntu docker ?)

If this helps you immediately, great. If you're still clueless, add some details on your error and we'll see if we can suggest something :)

**Comment by ArthurNRL** [comment]
Yes it is, and we need it since it is a program developed for windows, any suggestion is appreciated

**Comment by ewjoachim** [comment]
I see the following in a changelog entry in the coverage docs:

https://coverage.readthedocs.io/en/7.2.3/changes.html#version-4-5-2018-02-03
> The coverage combine command could get confused about path separators when combining data collected on Windows with data collected on Linux, as described in [issue 618](https://github.com/nedbat/coveragepy/issues/618). This is now fixed: the result path always uses the path separator specified in the [paths] result.

Here's the related issue: https://github.com/nedbat/coveragepy/issues/618
Here's the related commit: https://github.com/nedbat/coveragepy/commit/69debd440daab9155cc2b2243f29a8a48f4404f9

Can you try specifying paths with forward slashes in your coverage config ? Does it work ? I'm afraid we're much in the territory of coverage here, and not of this action.

**Comment by ArthurNRL** [comment]
Thank you! Adding:
```
[paths]
source =
    */alteryx_xml_tool/alteryx_xml_tool
    *\alteryx_xml_tool\alteryx_xml_tool
```
to .coveragerc did the trick. 
Maybe you could consider adding that to your docs or maybe even some handling in the code!
Thanks again.

**Comment by ewjoachim** [comment]
@ArthurNRL Feel like doing a PR for updating the docs ?

**Comment by ArthurNRL** [comment]
@ewjoachim https://github.com/ArthurNRL/python-coverage-comment-action/pull/1 here it is
