### ISSUE TITLE
No coverage comment

### ISSUE THREAD

**Issue by beataburczyk** [py-cov-action/python-coverage-comment-action#167]
Hello, I have tried to debug this problem but run out of ideas. Base on exception message I see what line is raising the error its referring to missing  GITHUB_TOKEN but its included 
```
#.github/workflows/pr-review.yml
name: Pull request auto review

on:
    pull_request:
      branches:
        - main

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # install dependencies
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # - name: Lint with flake8
      #   run: |
      #     make lint
      - name: Test with coverage
        run: |
          make test
          cd src
          ls -al
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

```
I was following readme file, and part responsible for github token looks good to me.
```
#/.github/workflows/coverage.yml
name: Post coverage comment

on:
  workflow_run:
    workflows: ["Pull request auto review"]
    types:
      - completed

jobs:
  test:
    name: Display coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      contents: write
      actions: read
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
```

Here is a full error with trackback
``` Notice: Starting action
Error: Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage
Otherwise please look for open issues or open one in https://github.com/py-cov-action/python-coverage-comment-action/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 17, in run
    return subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('coverage', 'json', '-o', '-')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 39, in main
    exit_code = action(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 75, in action
    coverage = coverage_module.get_coverage_info(merge=config.MERGE_COVERAGE_FILES)
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/coverage.py", line 75, in get_coverage_info
    json_coverage = subprocess.run("coverage", "json", "-o", "-")
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line [25](https://github.com/org/repo/actions/runs/4864464278/jobs/8673513037#step:7:26), in run
    raise SubProcessError("\n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: No data to report.
```

And bit of my test and coverage step what according to logs doing the job well.
Source code is located in /src and tests are located at /src/tests
Coverage config file
```
#/src/.coveragerc with content
[run]
relative_files = True
```

More step output

``` Run make test
  
cd src; pipenv run coverage run -m pytest -v tests/
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/runner/.local/share/virtualenvs/repo-name

============================= 28 passed in 26.59s ==============================
cd src; pipenv run coverage report -m

--------------------------------------------------------------------------
TOTAL                                          [75](https://github.com/repo-name/actions/runs/4864464278/jobs/8673513037#step:6:76)6     29    96%
total 112
drwxr-xr-x 4 runner docker  4096 May  2 18:21 .
drwxr-xr-x 8 runner docker  4096 May  2 18:20 ..
-rw-r--r-- 1 runner docker 53248 May  2 18:21 .coverage
-rw-r--r-- 1 runner docker    27 May  2 18:20 .coveragerc
drwxr-xr-x 3 runner docker  4096 May  2 18:21 .pytest_cache
-rw-r--r-- 1 runner docker     0 May  2 18:20 __init__.py
```
Sorry but I had to cut off filenames and repo name due to being private repo, but as pytest run with no problem, and I see .coverage file is created, I struggle to understand why subprocess try to generate report one more time and its failing, any ideas?

Will appreciate any hints ;)

**Comment by kieferro** [comment]
The fact that the warning points to the Github token is just the default for unknown errors because some things have changed for the permissions and that is the most common source of errors. But there is no checking logic behind it and in this case it doesn't look like that is the problem.

The Subprocess command that throws the error tries to generate a percentage value for the total coverage from the coverage data in the `.coverage` file. Thereby different errors can occur. But what looks most likely to me in this case is that the `.coverage` file is not in the folder where the action is executed. After all, each workflow step is always started in the same folder, regardless of where the one before it `cd`ed to. And if I see it correctly, the coverage data is generated in `/src/`. Could this be the problem?

If that is the case, then you could try copying the `.coverage` file to the default directory where the action is executed.

**Comment by beataburczyk** [comment]
Make sense now. This default error message was confusing to me.
In meantime I have experimented with other repo with partial success.
In this repo code is located in src folder too but coverage executed in different way and this confirms what you says.
Thank you for your time.

**Comment by ewjoachim** [comment]
I wonder if we should allow specifying a folder for .coverage... @kieferro any idea?

**Comment by ewjoachim** [comment]
(☝️ wrong backlink sorry)

**Comment by kieferro** [comment]
> I wonder if we should allow specifying a folder for .coverage... @kieferro any idea?

Yes, that is a good suggestion. I suppose we could just use the `--data-file` option when generating the coverage data if a specific folder is passed as argument.

**Comment by ewjoachim** [comment]
I wonder if it's the same to use `--data-file` or to cd to the folder. I guess coverage might consider where to plug relative paths differently in either case

**Comment by ewjoachim** [comment]
(I've started working on this, but no idea when I'll take the time to finish it)

**Comment by kieferro** [comment]
@ewjoachim Nice 😃, I actually wanted to take care of it too and then other things came up. Do as much as you like, but if at any point you don't have enough time to finish it, feel free to push all your stuff and notify me. Then I can take care of the rest
