### ISSUE TITLE
bug: not all annotations are posted to PR

### ISSUE THREAD

**Issue by MartinBernstorff** [py-cov-action/python-coverage-comment-action#186]
E.g. https://github.com/Aarhus-Psychiatry-Research/psycop-common/actions/runs/5241351155/jobs/9463329902

for this PR: https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/101

Line 45 in `src/psycop/common/model_evaluation/markdown/md_objects.py` is missing coverage, but does not have an annotation posted.

Anything I can do to help? :-)

**Comment by ewjoachim** [comment]
Hm, from looking quickly at the PR you sent, diff coverage seems to say that 100% of new lines are covered. Do you have something that tells you for sure that this line is NOT covered ?

**Comment by MartinBernstorff** [comment]
Ah sorry, I updated the PR to improve the coverage, which updated the comment and annotations. My bad!

I've created another PR to show the issue: https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/102

**Comment by kieferro** [comment]
I'm not sure if this is actually a bug in the action itself. [The logs show that over 1000 warnings were issued](https://github.com/Aarhus-Psychiatry-Research/psycop-common/actions/runs/5241351155/jobs/9463329902#step:10:1010). However, only 20 of them are displayed as annotations [in the file view](https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/102/files). I could imagine that there is a limit for the annotations. [This community post](https://github.com/orgs/community/discussions/26680) seems to confirm that, but I can't find much more about it.

**Comment by ewjoachim** [comment]
@MartinBernstorff Would you want to try you hand at making a PR for this ?

**Comment by MartinBernstorff** [comment]
Absolutey, taken a stab over at #188.

**Comment by kieferro** [comment]
Reopened by #193

**Comment by ewjoachim** [comment]
This is supposedly fixed by https://github.com/py-cov-action/python-coverage-comment-action/pull/212 but please don't hesitate to repoen if need be.
