### ISSUE TITLE
Could not find the branch to compare to.

### ISSUE THREAD

**Issue by wistuba** [py-cov-action/python-coverage-comment-action#192]
This action started failing just today claiming the branch would not exist: https://github.com/awslabs/Renate/actions/runs/5290184917/jobs/9574388465?pr=304

Related to #188 ?

**Comment by ARodenboog** [comment]
Same issue here

**Comment by gst** [comment]
same here, I see a newer docker image (despite still tagged same) was fetched to build : 

before:

```
 Digest: sha256:0cc567d530674237b8372e9f378fc1fa22d0b7b04994f8873bb9c7567e62fcd5
  Status: Downloaded newer image for ewjoachim/python-coverage-comment-action-base:v1
```

now:

```
  Digest: sha256:c6eb5673e560082a62d14af8c2bd6ca6e81f9f0363c37fcc677be4440dabb039
  Status: Downloaded newer image for ewjoachim/python-coverage-comment-action-base:v1
```

**Comment by kieferro** [comment]
Sorry for the inconvenience and for the late response. We obviously got something mixed up in #188. I have deployed the revert of #188 as a quickfix. That should fix all the problems and we are now looking deeper into the reasons and causes for this problem.
