### ISSUE TITLE
Automatically tag new releases to allow version pinning

### ISSUE THREAD

**Issue by MartinBernstorff** [py-cov-action/python-coverage-comment-action#196]
As mentioned in the readme, this seems relatively high priority. 

I'd  propose someting like semver based on git history:

https://github.com/marketplace/actions/git-semantic-version

And then use that as input to an automatic release action:

https://github.com/marvinpinto/action-automatic-releases

**Comment by ewjoachim** [comment]
(relevant issue: https://github.com/py-cov-action/python-coverage-comment-action/issues/35 )

**Comment by ewjoachim** [comment]
Pointing to #233 as a relevant discussion. Let's continue the discussion over there.
