### ISSUE TITLE
Instructions for running built docker container.

### ISSUE THREAD

**Issue by dmarkey** [py-cov-action/python-coverage-comment-action#268]
Hey, thanks for the action!

I'm trying to figure out how to use the build docker container version to save build times, but it doesnt seem to be a drop in replacement:

```
- name: Coverage Report
      if: inputs.skip-coverage == 'false'
      id: coverage_comment
      uses: docker://docker.io/ewjoachim/python-coverage-comment-action:v2
      with:
          GITHUB_TOKEN: ${{ inputs.gh-token }}
          COVERAGE_PATH: ${{ inputs.project-root }}
 ```

Results in:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/settings.py", line 167, in from_environ
    config_obj = cls(**config)
                 ^^^^^^^^^^^^^
TypeError: Config.__init__() missing 2 required keyword-only arguments: 'GITHUB_TOKEN' and 'GITHUB_PR_RUN_ID'
During handling of the above exception, another exception occurred:
```

So maybe I need to provide different config parameters for the built docker image version..

**Comment by dmarkey** [comment]
Aha! seems that inputs kinda don't work with a docker image that isnt built from scratch, so env variables need to be used, supplying these env variables worked:

```
      env:
          GITHUB_TOKEN: ${{ inputs.gh-token }}
          COVERAGE_PATH: ${{ inputs.project-root }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
```

(coverage path optional)

**Comment by ewjoachim** [comment]
That's an interesting use case, but I can't promise we won't accidentally break it in the future, as we're not testing for that use case in particular.

For curiosity, how much is it saving on your build ? Given that you're doing the same thing as GHA does, I'd have expected for it to take roughly as long ?

**Comment by ewjoachim** [comment]
(also, you're using the `:v2` image. You may have noticed that there are newer versions)

**Comment by ewjoachim** [comment]
Oh, I just realized: we're only pushing https://hub.docker.com/repository/docker/ewjoachim/python-coverage-comment-action-base/general and not https://hub.docker.com/repository/docker/ewjoachim/python-coverage-comment-action/general which is a leftover of our previous deployment process. You'll be on your own with this image :/

That said, if you want to submit a PR for pushing this image as well as the base image, you're welcome

**Comment by ewjoachim** [comment]
I have a counter-proposal:
Here's the dockerfile we build for every action: https://github.com/py-cov-action/python-coverage-comment-action/blob/main/Dockerfile#L5
We could skip the whole `pip install` in many cases (e.g. if the base image is recent enough (/ hasn't changed)) That's probably trivial to implement in the Dockerfile, and it could make the build faster than the 12s it is today.
