### ISSUE TITLE
`parse_diff_output()` raises AssertionError in v3.12

### ISSUE THREAD

**Issue by atenni** [py-cov-action/python-coverage-comment-action#275]
Hello, and thanks for creating this GH Action! I have a workflow that fails on v3.12 but succeeds on v3.11...

<details>
<summary>Stack trace from failing workflow run when using v3.12...</summary>

```bash
Notice: Generating comment for PR
Error: Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage
Otherwise please look for open issues or open one in https://github.com/py-cov-action/python-coverage-comment-action/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 40, in main
    exit_code = action(
                ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 92, in action
    return process_pr(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 121, in process_pr
    added_lines = coverage_module.get_added_lines(git=git, base_ref=base_ref)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/coverage.py", line 279, in get_added_lines
    return parse_diff_output(diff)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/coverage.py", line 291, in parse_diff_output
    assert current_file
AssertionError
```

</details>

It falls over on the line below, where it looks like `current_file` never gets updated: https://github.com/py-cov-action/python-coverage-comment-action/blob/08f2d84b93f75ccaf3431cefae8690571965981c/coverage_comment/coverage.py#L291

Here's an example of an input `diff` for this function that fails on v3.12, but passes when I pin the action to v3.11:

<details>
<summary>Sample diff for `parse_diff_output()`...</summary>

> **Note**
> This diff was created by inserting the following step into the workflow directly before the `python-coverage-comment-action` step:
>
> ```yaml
>      - name: Debug CI on host
>        run: |
>          sudo apt-get install -y tree \
>            && tree -a . \
>            && git fetch origin dev --depth=1000 \
>            && git diff --unified=1 FETCH_HEAD -- .
> ```
>
> Let me know if you want to see the output of `tree`, but all the files are found as expected.

Sample diff:

```bash
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 7c0e612..e4ddca1 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,2 +75,17 @@ jobs:
         run: docker exec $CONTAINER_NAME yarn lint
+      
+      - name: Debug CI in container
+        run: |
+          docker exec $CONTAINER_NAME \
+            yum install -y tree \
+            && tree -a . \
+            && git fetch origin dev --depth=1000 \
+            && git diff --unified=1 FETCH_HEAD -- .
+
+      - name: Debug CI on host
+        run: |
+          sudo apt-get install -y tree \
+            && tree -a . \
+            && git fetch origin dev --depth=1000 \
+            && git diff --unified=1 FETCH_HEAD -- .
```

</details>

If it makes a difference this is from a PR where a feature branch is getting merged into `dev`. We use `master` as our default branch. Also, we haven't yet run this action on `master` so don't yet have the `python-coverage-comment-action-data` branch.

Unfortunately this is in a private work repo so I can't give links, but let me know if you need any more info.

Cheers,
Andrew.

**Comment by ewjoachim** [comment]
@atenni Thanks for the debug efforts! I've made a PR where we add more logs: #276 
As soon as tests pass, I'll release it, and you'll be able to re-run your workflow and see exactly how the diff appears to be different from expected. I've tried passing the diff you submitted to the parse function, but it seems to work as expected.
![Screenshot from 2023-09-26 09-05-11](https://github.com/py-cov-action/python-coverage-comment-action/assets/1457576/b1d67f6e-c7ca-4954-b6d1-881c60abff30)

**Comment by ewjoachim** [comment]
Here you are: https://github.com/py-cov-action/python-coverage-comment-action/releases/tag/v3.13

Let us know :)

**Comment by atenni** [comment]
Thanks, here's the output of the ValueError.

It looks like `parse_diff_output()` trips when the change is a file deletion.

In the first block below we deleted `.coveragerc` when we moved the config into pyproject.toml, and so the function never finds the expected `+++ b/` string:

```
ValueError: Unexpected diff output format: 
diff --git a/.coveragerc b/.coveragerc
deleted file mode 100644
index 62c7c38..0000000
--- a/.coveragerc
+++ /dev/null
@@ -1,7 +0,0 @@
-[report]
-exclude_lines =
-    # Use to ignore code which would only test that an externally written library is working correctly
-    # e.g. don't need to test if the requests library is pulling data correctly
-    pragma: no cover
-    # Function specific code
-    def lambda_handler
diff --git a/.devcontainer/devcontainer.json b/.devcontainer/devcontainer.json
index f6f0024..d18306e 100644
--- a/.devcontainer/devcontainer.json
+++ b/.devcontainer/devcontainer.json
@@ -16,3 +16,9 @@
-	// Set *default* container specific settings.json values on container create.
-	"settings": {
-		"terminal.integrated.shell.linux": null
+	"customizations": {
+		"vscode": {
+			// Set *default* container specific settings.json values on container create.
+			"settings": {
+				"terminal.integrated.shell.linux": null
+			},
+			// Add the IDs of extensions you want installed when the container is created.
+			"extensions": []
+		}
@@ -20,2 +25,0 @@
-	// Add the IDs of extensions you want installed when the container is created.
-	"extensions": [],
@@ -33 +37 @@
-		"PYTHONPATH": "/app/src/libs/"
+		"PYTHONPATH": "/app/src/libs:/app/src/lambda/add_fees"
diff --git a/.flake8 b/.flake8
new file mode 100644
index 0000000..782e11f
--- /dev/null
+++ b/.flake8
@@ -0,0 +1,13 @@
+# Note: the flake8 project has decided to not use the standardised `pyproject.toml`
+# for configuration, so we have to use this file instead. See:
+#   - https://github.com/PyCQA/flake8/issues/234
+#   - https://github.com/PyCQA/flake8/pull/1332
+#   - https://github.com/PyCQA/flake8/issues/1421
+#   - https://github.com/PyCQA/flake8/issues/1431
+#   - https://github.com/PyCQA/flake8/issues/1447
+#   - https://github.com/PyCQA/flake8/issues/1501
+
+[flake8]
+# See also pyproject.toml -> [tool.autopep8].max_line_length
+max-line-length = 150
+show-source = True
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index c2c2e9e..c605747 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,0 +17,8 @@ jobs:
+    permissions:
+      # Gives the action the necessary permissions for publishing new
+      # comments in pull requests.
+      pull-requests: write
+      # Gives the action the necessary permissions for pushing data to the
+      # python-coverage-comment-action branch, and for editing existing
+      # comments (to avoid publishing multiple comments in the same PR)
+      contents: write
@@ -20,2 +28,3 @@ jobs:
-      - id: cache-docker
-        name: Build local image cache
+
+      - name: Build local image cache
```

**Comment by kieferro** [comment]
Yes, you're right, we didn't consider that case. I have changed the code accordingly and [v3.14](https://github.com/py-cov-action/python-coverage-comment-action/releases/tag/v3.14) shouldn't have this problem anymore.
Just let us know if everything is working well now

**Comment by atenni** [comment]
Success - I can confirm everything works as expected when pinned to 3.14. Thanks @kieferro :)
