### ISSUE TITLE
0% coverage report instead of actual percentage

### ISSUE THREAD

**Issue by pdecat** [py-cov-action/python-coverage-comment-action#384]
Hi, the coverage on our project is reported as 0% in the [HTML report](https://htmlpreview.github.io/?https://github.com/claranet/tfwrapper/blob/python-coverage-comment-action-data/htmlcov/index.html) and [badge](https://raw.githubusercontent.com/claranet/tfwrapper/python-coverage-comment-action-data/badge.svg) while the [`coverage report` command](https://github.com/claranet/tfwrapper/actions/runs/8364151688/job/22898778094#step:5:140) does produce non-zero results:

![image](https://github.com/py-cov-action/python-coverage-comment-action/assets/318490/796e57c2-7a38-44b4-a125-f586b0fdddaa)

```
coverage: commands[1]> coverage report
Name                                 Stmts   Miss  Cover
--------------------------------------------------------
src/claranet_tfwrapper/__init__.py     861    182    79%
src/claranet_tfwrapper/azure.py         84     27    68%
src/claranet_tfwrapper/utils.py         10      0   100%
--------------------------------------------------------
TOTAL                                  955    209    78%
```

I've checked the [relevant parts](https://github.com/claranet/tfwrapper/blob/master/.github/workflows/main.yml#L35-L103) of our Github Actions CI, notably `relative_files = true` is set.  And compared that to the provided examples:
* https://github.com/py-cov-action/python-coverage-comment-action-v3-example/blob/main/.github/workflows/ci.yml
* https://github.com/py-cov-action/python-coverage-comment-action?tab=readme-ov-file#merging-multiple-coverage-reports

There is no warning when coverage is [collected](https://github.com/claranet/tfwrapper/actions/runs/8364151688/job/22898778094#step:5:144):
```
  coverage: OK (28.25=setup[1.20]+cmd[26.74,0.15,0.16] seconds)
  congratulations :) (28.50 seconds)
```

Nor when it is [processed](https://github.com/claranet/tfwrapper/actions/runs/8364151688/job/22898834415#step:5:22):
```
Notice: Starting action
Notice: HTTP Request: GET https://api.github.com/repos/claranet/tfwrapper "HTTP/1.1 [20](https://github.com/claranet/tfwrapper/actions/runs/8364151688/job/22898834415#step:5:21)0 OK"
Notice: Computing coverage files & badge
Notice: HTTP Request: GET https://img.shields.io/static/v1?label=Coverage&message=0%25&color=red "HTTP/1.1 200 OK"
Notice: Generating HTML coverage report
Notice: Saving coverage files
Notice: Files saved
Notice: You can browse the full coverage report at:
    https://htmlpreview.github.io/?https://github.com/claranet/tfwrapper/blob/python-coverage-comment-action-data/htmlcov/index.html
```

Right now, I'm a bit clueless about what could be wrong.
Any idea? :pray:

**Comment by ewjoachim** [comment]
Hello,

Indeed, something seems strange here.

I downloaded the 5 artifacts uploaded [here](https://github.com/claranet/tfwrapper/actions/runs/8393180795?pr=353), then cloned your repo, and launched `coverage combine` and `coverage report` and it says...

```console
$ coverage report               
Name                                 Stmts   Miss  Cover
--------------------------------------------------------
src/claranet_tfwrapper/__init__.py     861    861     0%
src/claranet_tfwrapper/azure.py         84     84     0%
src/claranet_tfwrapper/utils.py         10     10     0%
--------------------------------------------------------
TOTAL                                  955    955     0%
```
So at least, there's nothing that causes that in the python-coverage-comment-action. Either it's a bug in coverage or a bug in the setup. That said, you've followed the instructions we setup, so I want to continue digging deeper.

**Comment by ewjoachim** [comment]
Would you mind trying if adding `COVERAGE_PATH: src/` is enough to solve your issue? If not, I'll fork and run my own experiments, but from looking at it, it seems by far as the most plausible lead.

**Comment by pdecat** [comment]
Will do ASAP, thanks!

**Comment by pdecat** [comment]
Thanks to your [comment](https://github.com/py-cov-action/python-coverage-comment-action/issues/384#issuecomment-2015747202), I've figured that the issue was caused by the fact that `relative_files = true` was set during the first coverage execution but not during `coverage combine` execution.

I've moved that option to the `.coveragerc` configuration file, added that file to git, and it resolved the issue.

https://htmlpreview.github.io/?https://github.com/claranet/tfwrapper/blob/python-coverage-comment-action-data/htmlcov/index.html

**Comment by ewjoachim** [comment]
Perfect, happy that I was any help :)

Happy covering !
