### ISSUE TITLE
Hidden files (i.e. `.coverage`) are now excluded by `upload_artifact` v3 & v4 by default

### ISSUE THREAD

**Issue by j-i-l** [py-cov-action/python-coverage-comment-action#470]
> From September 2nd, 2024, we will no longer include hidden files and folders as part of the default upload of the v3 and v4 upload-artifact actions. This reduces the risk that credentials are accidentally uploaded into artifacts. Customers who need to continue to upload these files can use a new option, ‘include-hidden-files’, to continue to do so.

_From [github changelog notice](https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/)_

The consequence of this:

When using the provided example workflows, the `upload_artifact` steps will ignore any `.coverage*` file.

---
 

One approach to address this could simply be to add the option `include-hidden-files` as option for the `upload_artifact` action in the provided examples.
Another approach might be to not create hidden files in the first place (e.g. setting `COVERAGE_FILE: "_coverage"`, or similar).

The latter approach would probably be better in line with the security policy that lead to the decision to ignore hidden files in artifacts in the first place.

**Comment by ewjoachim** [comment]
damn.

Do you want to do the contribution to the README ?

**Comment by j-i-l** [comment]
@ewjoachim sure, why not!

**Comment by ewjoachim** [comment]
Fixed by #471 (I also added a small comment regarding the security aspect you mentioned)
