### ISSUE TITLE
401 unauthorized error building docker image

### ISSUE THREAD

**Issue by mariaines** [py-cov-action/python-coverage-comment-action#483]
We are using py-cov-action/python-coverage-comment-action@v3. Just started getting this error in our workflows:

```
/usr/bin/docker build -t b5c86f:646c26769b564c28b3472eebdb5a7171 -f "/home/runner/work/_actions/py-cov-action/python-coverage-comment-action/v3/Dockerfile" "/home/runner/work/_actions/py-cov-action/python-coverage-comment-action/v3"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 245B done
  #1 DONE 0.0s
  
  #2 [auth] ewjoachim/python-coverage-comment-action-base:pull token for registry-1.docker.io
  #2 DONE 0.0s
  
  #[3](https://github.com/shadowpuppet/reloaded/actions/runs/11077471336/job/30782787497?pr=3028#step:3:3) [internal] load metadata for docker.io/ewjoachim/python-coverage-comment-action-base:v6
  #3 ERROR: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aewjoachim%2Fpython-coverage-comment-action-base%3Apull&service=registry.docker.io: [4](https://github.com/shadowpuppet/reloaded/actions/runs/11077471336/job/30782787497?pr=3028#step:3:4)01 Unauthorized
  ------
   > [internal] load metadata for docker.io/ewjoachim/python-coverage-comment-action-base:v[6](https://github.com/shadowpuppet/reloaded/actions/runs/11077471336/job/30782787497?pr=3028#step:3:6):
  ------
  Dockerfile:2
  --------------------
     1 |     # See Dockerfile.build for instructions on bumping this.
     2 | >>> FROM ewjoachim/python-coverage-comment-action-base:v6
     3 |     
     4 |     COPY coverage_comment ./coverage_comment
  --------------------
  ERROR: failed to solve: ewjoachim/python-coverage-comment-action-base:v6: failed to resolve source metadata for docker.io/ewjoachim/python-coverage-comment-action-base:v6: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aewjoachim%2Fpython-coverage-comment-action-base%3Apull&service=registry.docker.io: 401 Unauthorized
```

**Comment by crimsonknave** [comment]
It looks like the `v6` tag (and v2-v5) are not present in docker hub: https://hub.docker.com/r/ewjoachim/coverage-comment-action/tags

**Comment by ewjoachim** [comment]
@crimsonknave you're talking about [hub.docker.com/r/ewjoachim/coverage-comment-action/tags](https://hub.docker.com/r/ewjoachim/coverage-comment-action/tags) instead of [hub.docker.com/r/ewjoachim/python-coverage-comment-action-base/tags](https://hub.docker.com/r/ewjoachim/python-coverage-comment-action-base/tags)

I can imagine the whole thing being a transient Docker Hub issue, is it still happening? I'm not seeing in in any repository using this action. Note: seeing your message, it seems your project is private so I can only guess. Do you do special docker login stuff in your workflow ?

**Comment by crimsonknave** [comment]
Whoops, you're right.

I can confirm that everything is working for me now. Does seem like some sort of transient issue.

**Comment by ewjoachim** [comment]
https://www.dockerstatus.com/pages/history/533c6539221ae15e3f000031

> September 27, 2024 13:47 PDT
September 27, 2024 20:47 UTC
[Investigating] Personal Access Tokens are failing to authenticate against Hub Registry., which includes pulls from GitHub Actions. Anonymous pulls and password auth continue to work.

> September 27, 2024 14:10 PDT
September 27, 2024 21:10 UTC
[Identified] Issue identified and fix applied, error rates are slowly returning to normal.

> September 27, 2024 14:20 PDT
September 27, 2024 21:20 UTC
[Monitoring] Access Tokens are working again, and error rates have returned to normal. Will continue to monitor.

> September 27, 2024 17:27 PDT
September 28, 2024 00:27 UTC
[Resolved] Access Token authentication has continued to be functional and stable.
