### ISSUE TITLE
Change behaviour when missing coverage data for the default branch

### ISSUE THREAD

**Issue by kieferro** [py-cov-action/python-coverage-comment-action#51]
It might be helpful to write in the PR-comment that there is no comparative data in PR mode if no coverage data for the default branch was found, instead of crashing the action. This would not lead to so much confusion when the action is set up by a PR (#15, #48).
This is nothing urgent, but something I wanted to put here so that I don't forget it.

**Comment by ewjoachim** [comment]
Great idea !

That said, the current code is already not supposed to crash the action. If it's crashing, there's a bug. I suspect, though, that even without crashing, it's displaying an exception traceback. We can make it less visible to avoid confusion.
