### ISSUE TITLE
Switch from dependabot to Renovate

### ISSUE THREAD

**Issue by ewjoachim** [py-cov-action/python-coverage-comment-action#69]
Renovate is more configurable and can automerge PRs.

See a configuration at https://github.com/procrastinate-org/procrastinate/blob/98804eed84f72cc2ee99295489baea9e2d3a6286/.github/renovate.json5 (Edited by @kieferro to link to merged branch instead of deleted branch).

Bonus points if we also use it to replace pre-commit autoupdate PRs (https://docs.renovatebot.com/modules/manager/pre-commit/) though I don't know how to disable those in pre-commit.ci.

**Comment by kieferro** [comment]
Switched in #70
