### ISSUE TITLE
optional annotations onto pull request for non covered lines

### ISSUE THREAD

**Issue by kapilt** [py-cov-action/python-coverage-comment-action#88]

**Comment by ewjoachim** [comment]
Could be interesting.

**Comment by ewjoachim** [comment]
So just to be sure, you're talking about [that](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message), right?

**Comment by ewjoachim** [comment]
Done by the extraordinary @kieferro (👏 ) in #96 

Please reopen if you were thinking about something else.

https://github.com/py-cov-action/python-coverage-comment-action#all-options
